### ISSUE TITLE
New feature: a bit more than "timers" ...

### ISSUE THREAD

**Issue by bttfba** [Heckie75/kodi-addon-timers#11]
All my previous requests come from the need to have an addon for building a kind of "television schedule", i.e. plan the playout of several video files during the day for the whole week. So, it could be a kind of idea for a new addon.
Practically it means to be able to schedule the play of a specific content (it could be a video, a movie, a picture, ...) at a specific time during the day and then another one at the end of the first and so on, filling all the day and possibly all the week with some video contents. And maybe some music during the night!
This need comes from the non-profit organization I'm working for, where we are trying to set up a kind of TV channel (inserted into the IPTV system) to be streamed inside an hospital, up to the rooms or even the beds of the patients, watching TV and feeling better!
What do you think? could it be feasible?
I'd like to know your opinion on this and, maybe, a possible plan and availability date, should you agree.
Thank you very much for your attention! Ciao
Fabio

**Comment by Heckie75** [comment]
@bttfba 

Actually I can take a look at your previous feature requests but I can't promise if and when I am going to implement these. I am very busy and there isn't too much spare time left. 

I am going to comment your feature requests but I won't program a more specialized or totally new addon.

**Comment by bttfba** [comment]
Thank you, Heckie75, i understand.
I'll try to suggest this activity as a new addon on the general Kodi forum, maybe there is someone willing to try

Thanks again, i'm going to close this issue
