### ISSUE TITLE
Non-related - Kodi Addon question

### ISSUE THREAD

**Issue by MarketingPip** [Heckie75/kodi-addon-timers#13]
Apologizes for opening an issue :( I added you to a repo hoping I can pick your brain! If you can jump in there or even send me e-mail etc here would be more than appreciated. ps; thank you very much for your add-on been using it for more than awhile & your work does not go un-appreciated.

**Comment by Heckie75** [comment]
Your welcome. What is the question?

**Comment by MarketingPip** [comment]
To be honest pretty dumping this in a repo where we can chat instead of blowing this up. (So I can just delete the repo after - and you can delete this issue / close this issue!). Sent you an invite - don't know if it went through tho.
