### ISSUE TITLE
Shutdown System after Sleeptimer expires (contextmenu)

### ISSUE THREAD

**Issue by Collabsvito** [Heckie75/kodi-addon-timers#16]
Hallo Heckie,

Ich möchte einen Einschlaftimer mit wenigen Klicks via Kontextmenü aus den Kodi Favoriten starten (die einzelnen Aktionen sollten vorher dauerhaft in den Einstellungen des Timerscriptes festgelegt werden).

Meine Vorgehensweise ist die folgende:
Ich gehe in die Einstellungen Deines "sript.timers" dort bleiben alle Aktionen von "Einschlafen" auf Standard bis auf "System Aktion nach Ablauf" diese setze ich auf "fahre System herunter". 

Wenn ich jetzt via Kontextmenü den Einschlaftimer starte wird das System nach der abgelaufenen Zeit nicht heruntergefahren und in den Einstellungen  des "script.timers" ist die "System Aktion nach Ablauf" wieder auf Standard = "keine" zurückgesetzt.

Mache ich irgendetwas falsch oder lässt sich der Einschlaftimer nicht so ausführen wie ich mir das vorstelle ?!

P.S. Klar könnte ich in der "set_sleep.py" die "SYSTEM_ACTION_NONE" mit der "SYSTEM_ACTION_POWEROFF" ersetzen (dann wäre diese Aktion jedoch dauerhaft festgelegt), aber ich würde das ganze lieber via den Einstellungen des "script.timers" umsetzen !

Gruß

**Comment by Heckie75** [comment]
@Collabsvito 
Ich arbeite gerade an der Version 3.3.0., in der wieder einiges umgebaut wird  Klingt sinnvoll eine Voreinstellung vornehmen zu können. Ich melde mich sobald es in einer pre-Version eingebaut ist.

**Comment by Heckie75** [comment]
@Collabsvito 
Ich habe das Feature eingebaut. Es ist in der version 3.3.0-pre2 enthalten, siehe https://github.com/Heckie75/kodi-addon-timers/tree/script.timers.3.3.0

Beachte, dass ich die Einstellungen des Addons komplett umgestellt habe. Falls Du die Pre-Version installierst und zu der stabilen / offiziellen Version zurückkehren möchtest, solltest Du vorher die Einstellungen des Addons sichern. 

Ich bin auf das Feedback gespannt.

**Comment by Collabsvito** [comment]
**@Heckie75** 
Super das nenn ich mal Service in der Servicewüste Deutschland !

Funktioniert so wie es soll.
Jetzt kommt die Sache mit dem kleinen Finger...:innocent:

Mir fehlt in den Einstellungen unter Einschlafen noch ein Schalter zur "Media Aktion" mit der Auswahl zwischen "Wiedergabeende abwarten" und Wiedergabe stoppen" (Standard).
Außerdem wünsche ich mir unter "Sonstiges" noch eine Einstellmöglichkeit für die Häufigkeit, die Dauer und ab wann die "Notifications" von KODI kurz vor dem Ablauf eines Timers/Einschlafen/Schlummer erscheinen sollen.

By the way: Was hat "Kodi herunterfahren" für eine Bedeutung ?
Ich kenne nur Kodi beenden/Neustart und "Kodi herunterfahren" bewirkt bei meiner Android-Box dasselbe wie der Befehl "System herunterfahren".

Vielen Dank erstmal für die gewünschte Umsetzung !:thumbsup:

**Comment by Heckie75** [comment]
@Collabsvito 

> Mir fehlt in den Einstellungen unter Einschlafen noch ein Schalter zur "Media Aktion" mit der Auswahl zwischen "Wiedergabeende abwarten" und Wiedergabe stoppen" (Standard).

Der Schalter "Wiedergabeende abwarten" ist m.E. nicht erforderlich. Bei Auswahl über EPG entspricht die Zeit exakt dem ausgewählten EPG Item, also der Dauer einer Sendung. Bei Auswahl auf allen anderen Elementen, z.B. PVR Kanal, Musik, Video wird explizit nach der Wiedergabezeit gefragt. Da der Timer ja ein Ende haben soll, ist die Dauer zwingend erforderlich. Allerdings kann diese nicht aus dem ausgewählten Medium (mit Ausnahme EPG) bestimmt werden, da Kodi diese erst kennt, wenn das Medium abspielt wird. der Aufwand der Umsetzung wäre erheblich. 

> Außerdem wünsche ich mir unter "Sonstiges" noch eine Einstellmöglichkeit für die Häufigkeit, die Dauer und ab wann die "Notifications" von KODI kurz vor dem Ablauf eines Timers/Einschlafen/Schlummer erscheinen sollen.

Ich verstehe die Anforderung so, dass bspw. 5 Minuten vor Ende des Timers eine Meldung kommen soll, dass der Timer abläuft. Oder 5 Minuten vor Start eines Timers auf den Start hingewiesen wird. Die Umsetzung ist nicht trivial, da die Auslösung von Notifications von den Auslösungen (Anfang, Ende) der Timer getrennt werden müsste.  Unabhängig davon finde ich die Anforderung interessant, die vielen Einstellungsmöglichkeiten können Nutzer aber auch überfordern. 

> By the way: Was hat "Kodi herunterfahren" für eine Bedeutung ?

Dies führt die Aktion aus, die in Kodi unter "Enstellungen > System > Energiesparen > Funktion für Ausschalten" hinterlegt ist.

**Comment by Collabsvito** [comment]
**@Heckie75** 
Okay das mit dem "Wiedergabeende abwarten" wäre jetzt auch nur so eine Art Bonus gewesen, aber muss auch nicht sein.

> da die Auslösung von Notifications von den Auslösungen (Anfang, Ende) der Timer getrennt werden müsste.

In den Einstellungen des Addons ist eine Trennung meines Erachtens nicht unbedingt erforderlich da ja nur der Zeitrahmen festgelegt wird egal ob vor dem festgelegten Start oder vor dem festgelegten Ende.

> Außerdem wünsche ich mir unter "Sonstiges" noch eine Einstellmöglichkeit für die Häufigkeit, die Dauer und ab wann die "Notifications" von KODI kurz vor dem Ablauf eines Timers/Einschlafen/Schlummer erscheinen sollen.

Vielleicht habe ich es mit der Häufigkeit der "Notification" auch etwas übertrieben, hier ein Beispiel:
Ich starte "Einschlafen" über das Kontextmenü, dann bekomme ich ja eine "Notification" über den Start des Timers (hier würde ich gerne die Dauer der Anzeige auf ca. 8 Sekunden erhöhen) und eine Minute vor Ablauf kommt eine weitere "Notification" über das Ende des Timers, den ich dann falls gewünscht über das Kontextmenü beenden kann.

Evtl. ähnlich wie es hier in den Einstellungen behandelt wird: [https://github.com/b-jesch/service.sleepy.watchdog/tree/Matrix](url)

Abgesehen von den Einstellmöglichkeiten fände ich grundsätzlich eine "Notification" vor dem Start (ist bei Einschlafen ja der Fall) bzw. dem Ablauf eines Timers/Einschlafen/Schlummer schon wichtig (Falls man es sich anders überlegt hat und den Timer noch kurzfristig stoppen möchte).
Falls der Scriptaufwand jedoch dadurch extrem ausarten würde, verstehe ich es wenn Du dies nicht umsetzt.

> Dies führt die Aktion aus, die in Kodi unter "Enstellungen > System > Energiesparen > Funktion für Ausschalten" hinterlegt ist.

Ah das war mich nicht unbedingt bewusst, obwohl ich ja nicht unbewandert bin was Kodi betrifft - jetzt ist mir klar warum dieselbe Aktion wie bei "System herunterfahren" ausgeführt wird.

**Comment by Heckie75** [comment]
@Collabsvito 
Ich könnte mir vorstellen, den Abbuch anzubieten, wenn das System "droht" herunterzufahren, sprich eine Systemaktion ausgeführt wird. Dies dürfte ziemlich einfach sein. Der Abbruch einer Medienwiedergabe ist ja weniger tragisch.

**Comment by Collabsvito** [comment]
**@Heckie75** 
Ja, genau Du hast es auf den Punkt gebracht (_verdammt hoffentlich merkt Keiner, dass ich nicht aus der Branche komme_) für eine Systemaktion halte ich die Möglichkeit eines Abbruchs schon für wichtig !
Und wie sieht Dein Konsens hierzu aus:

> dann bekomme ich ja eine "Notification" über den Start des Timers (hier würde ich gerne die Dauer der Anzeige auf ca. 8 Sekunden erhöhen) und eine Minute vor Ablauf kommt eine weitere "Notification" über das Ende des Timers

**Comment by Heckie75** [comment]
@Collabsvito 
Ich habe eine solche Abfrage eingebaut, wenn eine Systemaktion ansteht. Siehe 3.3.0-pre3, https://github.com/Heckie75/kodi-addon-timers/tree/script.timers.3.3.0

Alle anderen Aktionen (Wiedergabe beenden etc.) werden trotzdem ausgeführt. 

> und eine Minute vor Ablauf kommt eine weitere "Notification" über das Ende des Timers

Die Umsetzung ist aufwändig. Eine solche Benachrichtigung ist m.E. nur dann wirklich sinnvoll, wenn der Nutzer eine Eingriffmöglichkeit hat. Weil ich den Nutzen nicht so sinnvoll finde und der Aufwand hoch ist, werde ich hier zunächst keine Zeit investieren. Da gibt es andere Dinge, die vorher umgesetzt werden müssen.

**Comment by Collabsvito** [comment]
**@Heckie75** 
Ich bin endlich mal dazu gekommen die Version 3.3.0-pre5 ausgiebig zu testen.
Die Meldung mit Eingriffsmöglichkeit für systemrelevante Aktionen finde ich sehr gut umgesetzt, meine Vorstellungen sind erfüllt.

Was die Übersicht und Klarheit der Einstellungen des Scriptes betrifft, sind diese nun sehr klar und nicht so überladen wie in der Version 3.1.0 dargestellt, wobei für den Normaluser eine Anzahl von max. 5 Timern bestimmt ausreichend wären.

Das einzige was ich als Perfektionist noch zu bemängeln hätte sind einige deutsche Übersetzungen:
z.B. fahre System herunter -> System herunterfahren, Gebe Startzeit ein -> Startzeit eingeben, Gebe die Endzeit des Timers ein -> Endzeit des Timers eingeben usw. 

Dies ist jetzt allerdings nicht unbedingt als Makel anzusehen, sondern als Ansicht eines Perfektionisten (_verdammt man kann es einfach nicht abstellen_).

Jedenfalls ist der Issue von meiner Seite hiermit erledigt und kann geschlossen werden !
Vielen Dank:sunglasses:

**Comment by Heckie75** [comment]
@Collabsvito 
Danke für das Testen und die Rückmeldung. Ich habe noch einige Übersetzungen angepasst. Dies ist in der Version pre6 zu sehen. Die neue Version werde ich voraussichtlich Mitte bis Ende August einreichen, so dass diese dann im offiziellen Repo ist.
