### ISSUE TITLE
user defined command e.g. CECStandby() 

### ISSUE THREAD

**Issue by Grruhn** [Heckie75/kodi-addon-timers#26]
Hi Heckie75,
your addon is great but I have a suggestion for a very useful feature. 
If you could run a custom command. I am using Kodi on a RPI 4 and would like to be able to turn off the TV using the addon. This is very easy to do with a CEC command. [CECStandby()]. Then the addon would be perfect :-)

Greetings from Mannheim

**Comment by Heckie75** [comment]
Maybe you would like to take a look at https://github.com/Heckie75/kodi-addon-timers/tree/script.timers.3.5.0

I've implemented for coming v3.5.0

Note, that it includes also feature #25 which is very fresh and has maybe still some bugs.

**Comment by Heckie75** [comment]
Feature is available in 3.5.0
