### ISSUE TITLE
Integration with other video addons

### ISSUE THREAD

**Issue by TermeHansen** [Heckie75/kodi-addon-timers#29]
I'm the developer of a video addon, and I would like to know how I can add the timer contextmenu to my playable items in my addon?

Also, is it possible for me to use this addon to run a daily task if nothing is playing by calling my addon with a specific parameter?

**Comment by Heckie75** [comment]
The context menu should be available on all items. But there is a mechanism that checks if this item can be scheduled. Take a look at [abstract_set_timer](https://github.com/Heckie75/kodi-addon-timers/blob/master/script.timers/resources/lib/contextmenu/abstract_set_timer.py#L115)

This code uses criterion that are implemented in [vfs_utils](https://github.com/Heckie75/kodi-addon-timers/blob/791fbb4a758882d9a7cd83ecb8c75ff77a4a2238/script.timers/resources/lib/utils/vfs_utils.py)

Maybe this helps to find out why the context menu doesn't work with you video addon. Let me know if I can help.

**Comment by TermeHansen** [comment]
@Heckie75  thks for the pointers, I'll dig in and find out why my items have no timer context items. Looking at your code, I would suggest you to checkout out the Path object from pathlib ([https://docs.python.org/3/library/pathlib.html](https://docs.python.org/3/library/pathlib.html)).

For my other question I would like to understand if I programmatically can update/add a timer from my addon directly. I would like to use this as a setting option for the user to add/remove a timer from my addon to run a update request-cache function I have in the my addon.

**Comment by Heckie75** [comment]
@TermeHansen 

As far as I understand you would like to update your cache once in a while. That is definately not the right use case für thie timers addon. You should handle it inside your addon directly, e.g. by implementing a so called _monitor_.

**Comment by TermeHansen** [comment]
Thks, I thought so that this addon is not meant for this way. I will have a look on your monitor implementation, and see if I can get what I'm looking for in this way.

I'll close this issue...
