### ISSUE TITLE
Translation with UTF-8 (french fr-fr)

### ISSUE THREAD

**Issue by Skypichat-kodi** [Heckie75/kodi-addon-timers#46]
I get a problem to obtain UTF-8 characters like "éèêà" in french string.py
So, it's not possible to show these characters in kodi.

**Comment by Heckie75** [comment]
@Skypichat-kodi  Is this problem related to the timers-addon or is it a general problem?

If it is related to timers then please send me the detailed error that is logged in kodi.log file.

**Comment by Skypichat-kodi** [comment]
"Timers" is the only one with this problem.
I don't see anything in the log to explain that.
I added in attachement: string.po, log and the visible bug in Kodi.
NB: the  french file isn't fully transalted.
It can be good to introduce your add-on in Kodi-Weblate. So it was more simply for translator users for multi-language.
[resource.language.fr_fr.zip](https://github.com/user-attachments/files/17688908/resource.language.fr_fr.zip)
[kodi.log](https://github.com/user-attachments/files/17688909/kodi.log)
![screenshot00001](https://github.com/user-attachments/assets/1cffa433-bdc8-4145-93d1-893cbd4d6efe)

**Comment by Heckie75** [comment]
@Skypichat-kodi 
Thanks for providing the translations. Your file had a encoding issue. I have added the missing translations by utilizing Google Gemini. The new version will be released soon, see https://github.com/xbmc/repo-scripts/pull/2684
