### ISSUE TITLE
Device wakeup

### ISSUE THREAD

**Issue by wanthalf** [Heckie75/kodi-addon-timers#6]
Is there any reason, why the playback methods in player.py do not include a `xbmc.executebuiltin('CECActivateSource')` call before `super().play(item)`? I do not want to have the TV on all the time just for the playback to start at the planned time. Now it's  impossible to use the timers as alarm clock.

In my case, an even better solution would be to use the RTC wakeup timer of my Odroid N2+, so that I could put the Kodi player into sleep as well. But I understand that's device specific. Anyway, a hook would be more than welcome - according to the docs, it just requires writing a unix timestamp into `/sys/class/rtc/rtc0/wakealarm`.

**Comment by Heckie75** [comment]
@wanthalf 
I have added the suggested code in v2.1.2 

Pls check if it works for you.

The official repositories' pull request of v2.1.1 is pending so that there is good chance that I can make a new PR with v2.1.2

**Comment by wanthalf** [comment]
Great! It is basically the same I have already inserted into the script manually and it worked for me.

Do you see any possibility to integrate the device wakeup, somehow? It would surely be quite complex, since in case of multiple and/or repeated timers, the next wakeup time in order would need to be set each time after the previous is activated. (And the order may vary a lot if there are multiple overlapping timers set.)

**Comment by Heckie75** [comment]
In terms of the device wakeup I am not sure. It is interisting but needs a refactoring how the addon works. At this moment it checks every 10 seconds if a timer is in period and starts it if it is not started yet. In case of the wake up use case it must be predictive. 

In addition it is device / OS specific. I am also not sure if it follows the policies of Kodi addons since as far as I know addons are not allowed to execute external commands and maybe write into the filesystem.

**Comment by Heckie75** [comment]
CECActivateSource fixed in 2.1.2

**Comment by Heckie75** [comment]
@wanthalf  

Some time ago you have asked for a feature to wake up your PC in case of scheduled media. In the meantime have developed another script that might help. It is a script that shuts down your system if it idles and wakes it up in time if required. It takes also scheduled media in Kodi into account. 

Maybe take a look at [Homeserver Power Saver](https://github.com/Heckie75/homeserver-power-saver).
