### ISSUE TITLE
New feature: looping the media during timed interval

### ISSUE THREAD

**Issue by bttfba** [Heckie75/kodi-addon-timers#9]
Setting a timer, you have to give a starting time and an ending time. Suppose the timed interval is longer than the media duration. It would be great to have the possibilty to chose what happens when the media ends: stop the play or start again, i.e. loop the media till the expiration of the timer
Thanks
Fabio

**Comment by Heckie75** [comment]
see https://github.com/Heckie75/kodi-addon-timers/issues/8#issuecomment-1064005468

**Comment by Heckie75** [comment]
Difficulty: medium
Estimation: approw. 0,5 days

**Comment by bttfba** [comment]
Thanks, please consider this as priority 2, after #7

**Comment by Heckie75** [comment]
Copied comment:

- repeat should be more limited: 
        - if "end after" is set to nothing, "repeat" should not be available
        - if "end after" is set to "duration" or to "time", then:
                  - if "duration" (or "time") is longer than the scheduled video, it should loop till the expiration of "duration" ot till "time"
                  - if "duration" (or "time") is shorter than the scheduled video, no loop, the scheduled video should be stopped after "duration" ("time") and no loop then

**Comment by Heckie75** [comment]
@bttfba 

Now I have already implemented the repeat functionality. It uses the repeat function of the player which makes it hopefully much easier than the resume thing. Take a look at https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre15.zip

PS: I will keep pre14 which seems to be a good working version with resume functionality.
